vars:
  BUNDLE_ID:
    default: io.ionic.starter.dev
  APP_DISPLAY_NAME:
    default: "[DEV] My App"
  APP_PRODUCT_NAME:
    default: "[DEV] My App"

platforms:
  android:
    incrementVersionCode: true
    xml:
      - resFile: values/strings.xml
        target: resources/string[@name="app_name"]
        replace: |
          <string name="app_name">$APP_DISPLAY_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="title_activity_main"]
        replace: |
          <string name="title_activity_main">$APP_DISPLAY_NAME</string>
      - resFile: values/strings.xml
        target: resources/string[@name="package_name"]
        replace: |
          <string name="package_name">$BUNDLE_ID</string>
      - resFile: values/strings.xml
        target: resources/string[@name="custom_url_scheme"]
        replace: |
          <string name="custom_url_scheme">$BUNDLE_ID</string>
  ios:
    targets:
      App:
        bundleId: $BUNDLE_ID
        displayName: $APP_DISPLAY_NAME
        productName: $APP_PRODUCT_NAME
        incrementBuild: true
